language: java
jdk: oraclejdk8
dist: trusty
services:
- docker
env:
  global:
  - secure: NDtTkubA/d2cMTQkm9nFEwyIR6ayCfP80IqXphoE1NO4H7ozVnnJshFhOaD/JuFYBGOaG2TZOz7QcMO0Hfcds/2tvkq7F8BzLDrIIbrUSdULQc7/5Wf69DUDh5s3PwLdsoZCdHLMwiGkLPXkuh9uPbdYtT7Y4rr2/ox42X7q9RT8MGUJ1CPMyOuY18wfF2uPNQeGG2fEnOHiuJSez0eV6Tu32Ia5o7r563I8I/1zPGHOegI5g/E+RVYpInFrfbKo7GC0JPAJsH9eeNlf2sZZ7wmZYI+WdufxQ6peGP/M7DJXKc4rWHEmmVqINVOTtnR55eXYBMd5+VOSRHEF2G28S+/x8/9lbjvL6o+h8h8A3HRewlFTSUI2VGSFJe1vASVll626xbBBmlNgarXZIBTow7XzNvt+Q68uhhtX41shqPpCRzvH3TdEyxFkeegSpxOUukWI0mP5kSAqqfxQGEI7y2CkxAlNmCIt5rXI9I2Sk5K/ANB66V/quRZeKU57TR04YMCFpHtdSdhWWQflq/2dn7gGpsvHCHTL30TgsU/ERhQKjWHSqW+TlCrqcHUyv3/dr6Iebwk6WaZX+4s8aOrK+1Yz9WyQsC2RLGyfK914U+MKcffGcXGnz+1mObDhvhTsTEWW01aGsHkQRUaynHWNkftZ2cI7vw9C0P8O4u1gMQE=
  - secure: qYaanjusAM5kWcF8z0k5MSzt4zS62yR2jF6fmz23rkpRpUe8xFdkNg2R3F1CL4iOdE5lJyIxLOtSf8aab+Qs9EjVyMt3OKZxb6RDJz6lRLGSLkqgVZ/FlBMc238zDH/rbWFzT11NCl/1S4JAXOI/TqNzfOaYHhefFx+b/k2+YiTpjPgQ5W82fSBnvjeEHkDJoBXmOcozV+7GMmyOmTeBqYeD/tEj0xlr8K/RdJx7uSDp8iu/qz6TXpLjaVXa2tRNOqrIq/9VCcital/VztSx9lXa4PAHaOpUZ2+9zGU5rcLIkUXHK/ELWnqNbwF1WAwrBQc1FzJ9u5i1Ne2yiH2qoUqipZRmEzXnL0rsISrKlvVGyGPCQlKJJ2KnXDLrNSXiMXLlF7HvTfD4ZM3gibOF5TRqnGrAGHgkpzlV5SsYI5dTFf9pFSFkoVa4epx8o7juW9NNBkkLFnNyf7hGDIo6tU8W22iZ+XcPJmD7q5Q/U5Gdbimq2Ro/TIF3Xbo87CPekUQd4oAP3zLsZJ1xcYU2GD+B9CwgF1/MigmOQtvOnwimiTv2bX72t7uqKN/1qXJYtEe+3rOPtesnk4yKCb6LelbXas8A2eb3ZxeGY/KuZJjlIIGRC13PsRpHC/zv6GS/zu4O6d82XSd4IObT2UnCeI7VTTlyXK+pndsVTM0Lrtg=
  - secure: HTXWaB4Mqj2Yx94ACdgxgv2hi5CXlx+p9Ph7X+R8Z4F36BSCLpA2IAKrlpvWwVZjpb4av3B4887tOIAysRF70+DYXA769UkchXznczKy/X2aS/67apBLPudZXcjpC+NrzzVEM/FvchPszaetV5IFCrn0RMeU9VHed80su1HoPKmNIy70eLLU41LROLZu/drn/HruFqag7gjJgbffyRilzk0KnoTBgxCdiIfXQk1a+MFnMMdyhOWn5XE+80cDkMuG8yjrej1d63acKHUcme00ZfNCdIuYAOP1+YLvCOdrv8e2Wv6YxIjzF0/459Q397HVTyIP4yF8BtoDOoqrsNJj6F14W3VLO+lCsWogwuDL0BBKDyu+IIN4OnEp7fV3w1RF/sjQqI1+JLlRL8ectmHZ97Hho2xzPdw5xHFm2OOaaBdsCHYjPdyyKYkEQYjbG04et45UvE9hToWTJybWxpDwhFiUob1MKJbloTws+GnsQkMLrDExGhBxuRw2ctpNzxHqfcJ/wHxSTxpQDsRgv9+dC37j5lGb4WXnZnzZ+oGFkEmgaLEgeQB23c/dQtd1MCpb0Z6MdOVdhAxlC2QechE5Oussza/OncjQE4Oogrv/gA1uyvDG+DK5s9dxENEkJI3rswffmhhIXLes9HgmTFJkJAvfb9p3vSB5J29V/wvReI4=
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: VBaKaJQApAJWOMJQHcqEfvoPe+FEOzCJ73zCQHTfa7p/N5+LLyoA5lMsfar58Wizy+J7m7SZ38af9pIVxYDAmJmMxBq0hdisM2dgTE69JOlcF12ATIdVQP9mj2NFAQ+hEMVXeNZLE//uUGOXwE6vh4ndZTJKUn5aysKtTRYPXGXjtNo7c74Lcky11qPcpBZcm5kZCSzzFGd41I7+5IWekY+AJtB2fKOtpsI47ugcGa/oYBHzv5yi9R7MeVeWyg5nD/xySrubnppbbvpE3itk7pN+zIuv43KsyHsIlfnm29JOfb9sTONt7dIZNQgSgwSvnQyOG9/4ihbFS/HxpyzVPuPmbtJlf7zGlVsE4tSrYxMOhrTvx84gRsAAptlKyNSn2POJx3L27LK7lrs8ngxVv8het/JPqc3uVvlaSbWrGCIBfLBhjsQc7DEpeA2BvtrN59TCQsIQ6Ku/mbo7XrHNrVnppXfT8jBsJLXguhSnNdEmjJaX6LmK5B0Ft2Y9hGZhAXu5XseET1IyUzVi5JehwAchV7IyJCoGn/sUmb1mzIRi2aB8EGSxT7cpQ+BzrMnMG5bOMdwh1ht9ti0B/ccpWDHdjx1HfikWsctfXhPUmUUU8oNmrkBA44hlqkjCOfKmCZZIvafA86CXuyz6i2PM5QrRfAAGG5cazumVGTR2Yz8=
addons:
  sonarcloud:
    organization: hydroblok
    token:
      secure: "$SONAR_TOKEN"
script:
- "./mvnw clean install -B"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=hydroblok/prototype
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: hydroblok-prototype
